#!/usr/bin/env python

import subprocess

try:
	temp = subprocess.check_output(["git", "describe", "--tags", "--long"]).decode('ascii').strip();
except:
	temp = "no-rev-data"

print( "// DO NOT EDIT THIS FILE. AUTOMATICALLY GENERATED")
print( "#define GIT_REV_DATA \"" + temp + "\"" )